(function(){
const Q=['Years with Organization','Job Satisfaction','Productivity Score','Absence Days','Weekly Hours','Annual Salary'];
const G=['Department','Work Arrangement','Education Level'];
function hash(s){let h=2166136261;for(let i=0;i<s.length;i++){h^=s.charCodeAt(i);h=Math.imul(h,16777619)}return h>>>0}
function rng(seed){let a=seed>>>0;return()=>{a+=0x6D2B79F5;let t=a;t=Math.imul(t^t>>>15,t|1);t^=t+Math.imul(t^t>>>7,t|61);return((t^t>>>14)>>>0)/4294967296}}
function normal(r){let u=0,v=0;while(!u)u=r();while(!v)v=r();return Math.sqrt(-2*Math.log(u))*Math.cos(2*Math.PI*v)}
const pick=(r,a)=>a[Math.floor(r()*a.length)], clamp=(x,a,b)=>Math.max(a,Math.min(b,x)), round=(x,d=0)=>Number(x.toFixed(d));
function generate(code){code=code.trim().toUpperCase();const seed=hash('DD1|'+code),r=rng(seed);const patterns=[
{id:'SAT_ABS',label:'Satisfaction and absence',desc:'Lower job satisfaction tends to accompany more absence days.',effect:'negative'},
{id:'SAT_PROD',label:'Satisfaction and productivity',desc:'Higher job satisfaction tends to accompany somewhat higher productivity.',effect:'positive'},
{id:'REMOTE_SAT',label:'Work arrangement and satisfaction',desc:'Remote employees tend to report somewhat higher satisfaction than on-site employees.',effect:'group'},
{id:'REMOTE_PROD',label:'Work arrangement and productivity',desc:'Hybrid/remote employees tend to have somewhat higher productivity than on-site employees.',effect:'group'},
{id:'DEPT_SAL',label:'Department and salary',desc:'Salary differs meaningfully by department.',effect:'group'},
{id:'TENURE_SAL',label:'Tenure and salary',desc:'Years with the organization tends to be positively related to salary.',effect:'positive'},
{id:'EDU_SAL',label:'Education and salary',desc:'Higher education categories tend to have higher salaries, with substantial overlap.',effect:'group'},
{id:'HOURS_PROD',label:'Hours and productivity',desc:'Weekly hours has a modest positive association with productivity.',effect:'positive'},
{id:'NULL_WORK',label:'Tempting null comparison',desc:'Work arrangement has little meaningful relationship with absence in this case.',effect:'null'}];
let p1=patterns[Math.floor(r()*patterns.length)],p2;do{p2=patterns[Math.floor(r()*patterns.length)]}while(p2.id===p1.id);const selected=[p1,p2];
const depts=['Operations','Sales','HR','IT','Finance'], works=['On-Site','Hybrid','Remote'], edus=['High School','Associate',"Bachelor's","Master's+"];
const deptBase={Operations:52000,Sales:57000,HR:55000,IT:72000,Finance:67000},eduAdd={'High School':0,'Associate':3500,"Bachelor's":9000,"Master's+":15000};
let rows=[];for(let i=1;i<=30;i++){let department=pick(r,depts),work=pick(r,works),education=pick(r,edus),years=round(clamp(5+5*normal(r),0,22),1);let sat=clamp(6.2+1.5*normal(r),1,10);if(selected.some(p=>p.id==='REMOTE_SAT'))sat+=(work==='Remote'?1:work==='On-Site'?-0.5:0.3);sat=round(clamp(sat,1,10),1);let hours=round(clamp(40+4*normal(r),28,55),1);let prod=74+8*normal(r);if(selected.some(p=>p.id==='SAT_PROD'))prod+=(sat-6)*2.0;if(selected.some(p=>p.id==='REMOTE_PROD'))prod+=(work==='Remote'?5:work==='Hybrid'?2:-2);if(selected.some(p=>p.id==='HOURS_PROD'))prod+=(hours-40)*0.7;prod=round(clamp(prod,35,99),0);let abs=Math.max(0,Math.round(5+3*normal(r)));if(selected.some(p=>p.id==='SAT_ABS'))abs=Math.max(0,Math.round(abs+(6.5-sat)*1.5));if(selected.some(p=>p.id==='NULL_WORK'))abs=Math.max(0,Math.round(5+3*normal(r)));let salary=deptBase[department]+years*1200+eduAdd[education]+normal(r)*5000;if(selected.some(p=>p.id==='TENURE_SAL'))salary+=years*900;if(selected.some(p=>p.id==='DEPT_SAL'))salary+=(department==='IT'?9000:department==='Operations'?-4000:0);if(selected.some(p=>p.id==='EDU_SAL'))salary+=eduAdd[education]*0.6;salary=Math.round(salary/500)*500;rows.push({'Employee ID':'E'+String(i).padStart(2,'0'),'Department':department,'Work Arrangement':work,'Education Level':education,'Years with Organization':years,'Job Satisfaction':sat,'Productivity Score':prod,'Absence Days':abs,'Weekly Hours':hours,'Annual Salary':salary})}
const influenceTypes=['salary','absence','productivity'];let inf=pick(r,influenceTypes),idx=Math.floor(r()*rows.length);if(inf==='salary')rows[idx]['Annual Salary']=Math.round((Math.max(...rows.map(x=>x['Annual Salary']))+45000+r()*25000)/500)*500;if(inf==='absence')rows[idx]['Absence Days']=Math.max(...rows.map(x=>x['Absence Days']))+12+Math.floor(r()*8);if(inf==='productivity')rows[idx]['Productivity Score']=clamp(Math.min(...rows.map(x=>x['Productivity Score']))-18,20,45);const verification=(hash(code+'|VERIFY')>>>0).toString(36).toUpperCase().padStart(7,'0').slice(0,4)+'-'+(hash(code+'|V2')>>>0).toString(36).toUpperCase().padStart(4,'0').slice(0,2);return{code,rows,selected,influence:{type:inf,index:idx,row:rows[idx]},verification}}
function mean(a){return a.reduce((s,x)=>s+x,0)/a.length}function median(a){let b=[...a].sort((x,y)=>x-y),m=Math.floor(b.length/2);return b.length%2?b[m]:(b[m-1]+b[m])/2}function variance(a){let m=mean(a);return a.reduce((s,x)=>s+(x-m)**2,0)/(a.length-1)}function mode(a){let m=new Map;for(let x of a)m.set(x,(m.get(x)||0)+1);let max=Math.max(...m.values()),modes=[...m].filter(x=>x[1]===max).map(x=>x[0]);return max===1?'No unique mode':modes.join(', ')}function fmt(v,k){if(k==='Annual Salary')return '$'+Math.round(v).toLocaleString();return Number.isInteger(v)?v:v.toFixed(2)}
function stats(rows,k){let a=rows.map(x=>Number(x[k])).filter(Number.isFinite);return{n:a.length,mean:mean(a),median:median(a),mode:mode(a),min:Math.min(...a),max:Math.max(...a),range:Math.max(...a)-Math.min(...a),variance:variance(a),sd:Math.sqrt(variance(a))}}
function renderTable(table,rows){let keys=Object.keys(rows[0]||{});table.querySelector('thead').innerHTML='<tr>'+keys.map(k=>'<th>'+k+'</th>').join('')+'</tr>';table.querySelector('tbody').innerHTML=rows.map(row=>'<tr>'+keys.map(k=>'<td>'+(k==='Annual Salary'?'$'+row[k].toLocaleString():row[k])+'</td>').join('')+'</tr>').join('')}
function csv(data){let keys=Object.keys(data.rows[0]);let text=[keys.join(','),...data.rows.map(row=>keys.map(k=>'"'+String(row[k]).replaceAll('"','""')+'"').join(','))].join('\n');let b=new Blob([text],{type:'text/csv'}),u=URL.createObjectURL(b),a=document.createElement('a');a.href=u;a.download='DataDetective_'+data.code.replace(/[^A-Z0-9_-]/g,'_')+'.csv';a.click();URL.revokeObjectURL(u)}
window.DataDetective={generate,stats,fmt,renderTable,Q,G};
const gen=document.getElementById('generate');if(!gen)return;let current=null;const codeEl=document.getElementById('caseCode'), table=document.getElementById('dataTable');const student=!!document.getElementById('download');
if(student){const one=document.getElementById('oneVar'),comp=document.getElementById('compareVar'),grp=document.getElementById('groupVar');Q.forEach(k=>{one.add(new Option(k,k));comp.add(new Option(k,k))});G.forEach(k=>grp.add(new Option(k,k)));document.getElementById('download').addEventListener('click',()=>current&&csv(current));document.getElementById('analyzeOne').addEventListener('click',()=>{let k=one.value,s=stats(current.rows,k);document.getElementById('oneResults').innerHTML=`<table><tr><th>n</th><th>Mean</th><th>Median</th><th>Mode</th><th>Range</th><th>Variance</th><th>SD</th></tr><tr><td>${s.n}</td><td>${fmt(s.mean,k)}</td><td>${fmt(s.median,k)}</td><td>${s.mode}</td><td>${fmt(s.range,k)}</td><td>${fmt(s.variance,k)}</td><td>${fmt(s.sd,k)}</td></tr></table>`});document.getElementById('compare').addEventListener('click',()=>{let k=comp.value,g=grp.value,levels=[...new Set(current.rows.map(x=>x[g]))];document.getElementById('groupResults').innerHTML='<table><tr><th>'+g+'</th><th>n</th><th>Mean</th><th>Median</th><th>SD</th></tr>'+levels.map(l=>{let s=stats(current.rows.filter(x=>x[g]===l),k);return `<tr><td>${l}</td><td>${s.n}</td><td>${fmt(s.mean,k)}</td><td>${fmt(s.median,k)}</td><td>${fmt(s.sd,k)}</td></tr>`}).join('')+'</table>'})}
gen.addEventListener('click',()=>{let c=codeEl.value.trim();if(!c){document.getElementById('caseInfo').textContent='Please enter a Case Code.';return}current=generate(c);renderTable(table,current.rows);document.getElementById('caseInfo').innerHTML=`Case Code: <strong>${current.code}</strong> &nbsp; • &nbsp; Verification Code: <strong>${current.verification}</strong>`;if(student){['download','analyzeOne','compare'].forEach(id=>document.getElementById(id).disabled=false)}window.dispatchEvent(new CustomEvent('dd-generated',{detail:current}))});
})();
